image: sphonic/scala:2.11.6


services:
  - sphonic/cassandra:2.1.3

env:
  # CI_PASSWORD is defined in the DroneCI repository settings
  - CI_USERNAME=buildbot


script:
  # switch to oracle jdk 8
  - sudo update-java-alternatives -s java-8-oracle
  - sbt -Dsbt.log.noformat=true test
  
cache:
  - /root/.ivy2/cache
